# Generated by Django 4.0.3 on 2022-03-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('adminID', models.CharField(db_column='adminID', max_length=32, verbose_name='管理员账号')),
                ('passWord', models.CharField(db_column='pass_word', max_length=32, verbose_name='密码')),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('bookName', models.CharField(max_length=20, verbose_name='书名')),
                ('subhead', models.CharField(max_length=20, verbose_name='副标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('translator', models.CharField(max_length=20, null=True, verbose_name='译者')),
                ('press', models.CharField(max_length=20, verbose_name='出版社')),
                ('publicationYear', models.IntegerField(verbose_name='出版年份')),
                ('ISBN', models.IntegerField(verbose_name='ISBN')),
                ('pagination', models.IntegerField(null=True, verbose_name='页数')),
                ('cover', models.ImageField(null=True, upload_to='', verbose_name='封面')),
                ('prospectus', models.TextField(null=True, verbose_name='内容简介')),
                ('location', models.CharField(max_length=20, null=True, verbose_name='收录位置')),
                ('quantity', models.IntegerField(null=True, verbose_name='总数')),
                ('surplus', models.IntegerField(null=True, verbose_name='剩余数')),
                ('weight', models.IntegerField(null=True, verbose_name='权重')),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('countTime', models.DateField(auto_now=True, verbose_name='统计时间')),
                ('borrowDataNow', models.IntegerField(verbose_name='今日借书人数')),
                ('returnDataNow', models.IntegerField(verbose_name='今日还书人数')),
                ('DataNow', models.IntegerField(verbose_name='在借人数')),
            ],
            options={
                'db_table': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Uesr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('userID', models.CharField(db_column='user_ID', max_length=32, verbose_name='用户账号')),
                ('passWord', models.CharField(db_column='pass_word', max_length=32, verbose_name='用户密码')),
                ('nickName', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('userName', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='用户性别')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('address', models.CharField(max_length=64, verbose_name='联系地址')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('face', models.ImageField(upload_to='', verbose_name='人脸信息')),
                ('regDate', models.DateField(auto_now=True, verbose_name='注册时间')),
                ('weChat', models.CharField(max_length=32, verbose_name='微信号')),
                ('credit', models.IntegerField(verbose_name='信誉分')),
                ('book1ID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='book1ID', to='backend_app.books')),
                ('book2ID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='book2ID', to='backend_app.books')),
            ],
            options={
                'db_table': 'Uesr',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('borrowDate', models.DateField(auto_now=True, verbose_name='借书日期')),
                ('returnDate', models.DateField(verbose_name='还书时间')),
                ('deadline', models.IntegerField(verbose_name='期限')),
                ('borrowerID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend_app.uesr')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
    ]
